#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Aero Commerce CLI Tool', '0.8.9');

if (method_exists($app, 'addCommand')) {
    $app->addCommand(new Aero\Cli\NewCommand);
} else {
    $app->add(new Aero\Cli\NewCommand);
}

try {
    $app->run();
} catch (Exception $e) {
}
